# Generated by Django 5.2 on 2025-04-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id_room_type", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("max_guests", models.IntegerField(default=1)),
                ("floors", models.CharField(blank=True, max_length=100)),
                ("view", models.CharField(blank=True, max_length=100)),
                ("amenities", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id_room", models.AutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=10)),
                ("phone_room", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                ("light_on", models.BooleanField(default=False)),
                ("ac_on", models.BooleanField(default=False)),
                ("ac_temperature", models.IntegerField(default=22)),
                ("tv_on", models.BooleanField(default=False)),
                ("curtains_open", models.BooleanField(default=True)),
                ("do_not_disturb", models.BooleanField(default=False)),
                ("door_locked", models.BooleanField(default=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.roomtype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomTypeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="room_images/")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rooms.roomtype",
                    ),
                ),
            ],
        ),
    ]
