# Generated by Django 5.2 on 2025-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_roomtype_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="perfect_for",
            field=models.TextField(blank=True),
        ),
    ]
