# Generated by Django 5.2 on 2025-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_roomtype_perfect_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtype",
            name="amenities",
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_features",
            field=models.TextField(blank=True),
        ),
    ]
