# Generated by Django 5.2 on 2025-05-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_remove_roomtype_amenities_roomtype_room_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ["room_type_id"]},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="id_room",
            new_name="room_id",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="id_room_type",
            new_name="room_type_id",
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="room_images/")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
