# Generated by Django 5.2 on 2025-04-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("primary_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("date_joined", models.DateField()),
                ("last_login", models.DateField()),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=70)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "guest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Accounts.guest",
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("receptionist", "Receptionist"),
                            ("housekeeping", "Housekeeping"),
                        ],
                        default="receptionist",
                        max_length=20,
                    ),
                ),
            ],
            bases=("Accounts.guest",),
        ),
    ]
