# Generated by Django 5.2 on 2025-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="address",
        ),
        migrations.AddField(
            model_name="guest",
            name="code_to_active",
            field=models.IntegerField(blank=True, default=99999),
        ),
        migrations.AddField(
            model_name="guest",
            name="country",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="guest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "male"), ("F", "famale")],
                default="male",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="time_zone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
