# Generated by Django 5.2 on 2025-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_remove_guest_address_guest_code_to_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={"ordering": ["primary_id"], "verbose_name": "User"},
        ),
        migrations.AlterField(
            model_name="guest",
            name="last_login",
            field=models.DateTimeField(),
        ),
    ]
