# Generated by Django 5.2 on 2025-04-20 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_alter_guest_options_alter_guest_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="date_joined",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
