# Generated by Django 5.2 on 2025-04-20 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_guest_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="date_joined",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
