# Generated by Django 5.2 on 2025-04-20 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_alter_guest_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="last_login",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
