# Generated by Django 5.2 on 2025-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_alter_guest_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="username",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
