# Generated by Django 5.2 on 2025-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0008_alter_guest_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="last_login",
            field=models.DateTimeField(blank=True),
        ),
    ]
