# Generated by Django 5.2 on 2025-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0009_alter_guest_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="last_login",
        ),
    ]
