# Generated by Django 5.2 on 2025-04-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0010_remove_guest_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="time_zone",
        ),
    ]
