# Generated by Django 5.2 on 2025-04-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0011_remove_guest_time_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="date_joined",
        ),
    ]
