# Generated by Django 5.2 on 2025-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0012_remove_guest_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="temp_password",
            field=models.CharField(default="#######", max_length=20),
        ),
    ]
