# Generated by Django 5.2 on 2025-04-23 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0013_guest_temp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="date_joined",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="guest",
            name="last_login",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
