# Generated by Django 5.2 on 2025-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0014_guest_date_joined_guest_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={"ordering": ["primary_id"], "verbose_name": "Guest"},
        ),
        migrations.AlterField(
            model_name="guest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "male"), ("F", "famale")],
                default="M",
                max_length=1,
            ),
        ),
    ]
