# Generated by Django 5.2 on 2025-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0015_alter_guest_options_alter_guest_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
    ]
