# Generated by Django 5.2 on 2025-05-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0016_alter_guest_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={"ordering": ["guest_id"], "verbose_name": "Guest"},
        ),
        migrations.RenameField(
            model_name="guest",
            old_name="primary_id",
            new_name="guest_id",
        ),
    ]
