# Generated by Django 5.2 on 2025-05-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0017_alter_guest_options_rename_primary_id_guest_guest_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={"ordering": ["primary_id"], "verbose_name": "Guest"},
        ),
        migrations.RenameField(
            model_name="guest",
            old_name="guest_id",
            new_name="primary_id",
        ),
    ]
