# Generated by Django 5.2 on 2025-05-04 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accounts", "0017_alter_guest_options_rename_primary_id_guest_guest_id"),
        ("rooms", "0005_alter_roomtype_options_rename_id_room_room_room_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("checkin_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "check_in_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Accounts.guest"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                ("checkout_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "check_out_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkinout.checkin",
                    ),
                ),
            ],
        ),
    ]
